export const sagaActions = {
  FETCH_MOVIES: 'FETCH_MOVIES',
  FETCH_MOVIE_RATING: 'FETCH_MOVIE_RATING',
  FETCH_PRODUCTS_CATEGORY: 'FETCH_PRODUCTS_CATEGORY',
  FETCH_PRODUCTS_BY_CATEGORY: 'FETCH_PRODUCTS_BY_CATEGORY',
  USER_LOGIN: 'USER_LOGIN',
};
